version: '3'
services:
  chatbot:
    environment:
      - TELEGRAM_ACCESS_TOKEN=6065911282:AAGGO0FXc_dhrXbGVJA-sNme2GBCvZ3xldo
      - REDIS_HOST=redis
      - REDIS_PASSWORD=comp7940passwordlab8
      - REDIS_REDISPORT=6379
      - CHATGPT_MODELNAME=gpt-35-turbo-16k
      - CHATGPT_ACCESS_TOKEN=5edc988a-5fa4-4638-ae98-ea749e1a86aa
      - CHATGPT_BASICURL=https://chatgpt.hkbu.edu.hk/general/rest
      - CHATGPT_APIVERSION=2024-02-15-preview
    build: .
    depends_on:
      - redis
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["/usr/local/etc/redis/redis.conf"]